// src/components/ProductGrid.vue
<template>
  <div class="product-grid">
    <ProductItem 
      v-for="product in products" 
      :key="product.id" 
      :product="product" 
      :updateOrder="updateOrder" 
    />
  </div>
</template>

<script>
import ProductItem from './ProductItem.vue';

export default {
  name: 'ProductGrid',
  components: {
    ProductItem
  },
  props: {
    products: {
      type: Array,
      required: true
    },
    updateOrder: {
      type: Function,
      required: true
    }
  }
}
</script>

<style>
@import './ProductGrid.css';
</style>

// src/components/ProductGrid.jsx
import React from 'react';
import ProductItem from './ProductItem.jsx';
import './ProductGrid.css';

function ProductGrid({ products, updateOrder }) {
  return (
    <div className="product-grid">
      {products.map(product => (
        <ProductItem 
          key={product.id}
          product={product}
          updateOrder={updateOrder}
        />
      ))}
    </div>
  );
}

export default ProductGrid;
