// src/components/ProductItem.vue
<template>
  <div class="product-item">
    <h3>{{ product.name }}</h3>
    <p>${{ product.price.toFixed(2) }}</p>
    <div class="quantity-control">
      <button @click="handleDecrement">-</button>
      <span>{{ quantity }}</span>
      <button @click="handleIncrement">+</button>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'ProductItem',
  props: {
    product: {
      type: Object,
      required: true
    },
    updateOrder: {
      type: Function,
      required: true
    }
  },
  setup(props) {
    const quantity = ref(0);

    const handleIncrement = () => {
      quantity.value += 1;
      props.updateOrder(props.product.id, quantity.value);
    };

    const handleDecrement = () => {
      if (quantity.value > 0) {
        quantity.value -= 1;
        props.updateOrder(props.product.id, quantity.value);
      }
    };

    return {
      quantity,
      handleIncrement,
      handleDecrement
    };
  }
}
</script>

<style>
@import './ProductItem.css';
</style>

// src/components/ProductItem.jsx
import React, { useState } from 'react';
import './ProductItem.css';

function ProductItem({ product, updateOrder }) {
  const [quantity, setQuantity] = useState(0);

  const handleIncrement = () => {
    const newQuantity = quantity + 1;
    setQuantity(newQuantity);
    updateOrder(product.id, newQuantity);
  };

  const handleDecrement = () => {
    if (quantity > 0) {
      const newQuantity = quantity - 1;
      setQuantity(newQuantity);
      updateOrder(product.id, newQuantity);
    }
  };

  return (
    <div className="product-item">
      <h3>{product.name}</h3>
      <p>${product.price.toFixed(2)}</p>
      <div className="quantity-control">
        <button onClick={handleDecrement}>-</button>
        <span>{quantity}</span>
        <button onClick={handleIncrement}>+</button>
      </div>
    </div>
  );
}

export default ProductItem;
